site_name: 宝贝回家
theme: readthedocs
pages:
- Overview: index.md
- 技术公益: lovelytech.md
- 宝贝回家项目介绍: baby.md
- 宝贝回家小程序: mina.md
- 宝贝回家小程序后台: mina-backend.md
- 小程序客服机器人: mina-robot.md
- 文档贡献: 03_how_to_github_pull_request.md
- 文档排版: 04_chinese_copywrite_guidelines.md
