site_name: 宝贝回家
site_description:  技术公益项目
repo_url: https://github.com/bbhj/intro

theme: readthedocs

pages:
- 概览: index.md
- 技术公益: lovelytech.md
- 宝贝回家项目介绍: baby.md
- 宝贝回家论坛: bbs.md
- 宝贝回家小程序: mina.md
- 宝贝回家小程序后台: mina-backend.md
- 小程序客服机器人: mina-robot.md
- 项目周报: 
        - 'ChangeLog': weekly/changelog.md
        - '周报预览': weekly/index.md
        - 'week 32': weekly/2018w32.md
        - 'week 34': weekly/2018w34.md
        - 'week 35': weekly/2018w35.md
        - 'week 41': weekly/2018w41.md
        - 'week 42': weekly/2018w42.md
- 文档贡献: 03_how_to_github_pull_request.md
- 文档排版: 04_chinese_copywrite_guidelines.md
